name: Java - Docker Build and Push Base Image

on:
#  push:
#    branches:
#      - master
#    paths:
#      - 'Dockerfile'
  workflow_dispatch:
    inputs:
      baseimage:
        description: 'Provide dockerfile name to create base image :: '
        required: true
        default: 'Dockerfile'
jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: images/centos/openjdk8/jre
   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: fabric8/java-centos-openjdk8-jre
        IMAGE_TAG: 1.9.7_OracleLinux_8.6
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
